// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _openhab_controls_HH_
#define _openhab_controls_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct openhab_controls : public sc_module {
    // Port declarations 38
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > inStream_TDATA;
    sc_in< sc_logic > inStream_TVALID;
    sc_out< sc_logic > inStream_TREADY;
    sc_in< sc_lv<4> > inStream_TKEEP;
    sc_in< sc_lv<4> > inStream_TSTRB;
    sc_in< sc_lv<1> > inStream_TUSER;
    sc_in< sc_lv<1> > inStream_TLAST;
    sc_in< sc_lv<1> > inStream_TID;
    sc_in< sc_lv<1> > inStream_TDEST;
    sc_out< sc_lv<32> > outStream_TDATA;
    sc_out< sc_logic > outStream_TVALID;
    sc_in< sc_logic > outStream_TREADY;
    sc_out< sc_lv<4> > outStream_TKEEP;
    sc_out< sc_lv<4> > outStream_TSTRB;
    sc_out< sc_lv<1> > outStream_TUSER;
    sc_out< sc_lv<1> > outStream_TLAST;
    sc_out< sc_lv<1> > outStream_TID;
    sc_out< sc_lv<1> > outStream_TDEST;
<<<<<<< HEAD
    sc_out< sc_lv<32> > thresholds_V_Addr_A;
    sc_out< sc_logic > thresholds_V_EN_A;
    sc_out< sc_lv<4> > thresholds_V_WEN_A;
    sc_out< sc_lv<32> > thresholds_V_Din_A;
    sc_in< sc_lv<32> > thresholds_V_Dout_A;
    sc_out< sc_logic > thresholds_V_Clk_A;
    sc_out< sc_logic > thresholds_V_Rst_A;
    sc_out< sc_lv<32> > outData_V_Addr_A;
    sc_out< sc_logic > outData_V_EN_A;
    sc_out< sc_lv<4> > outData_V_WEN_A;
    sc_out< sc_lv<32> > outData_V_Din_A;
    sc_in< sc_lv<32> > outData_V_Dout_A;
    sc_out< sc_logic > outData_V_Clk_A;
    sc_out< sc_logic > outData_V_Rst_A;
=======
    sc_out< sc_lv<32> > thresholds_Addr_A;
    sc_out< sc_logic > thresholds_EN_A;
    sc_out< sc_lv<4> > thresholds_WEN_A;
    sc_out< sc_lv<32> > thresholds_Din_A;
    sc_in< sc_lv<32> > thresholds_Dout_A;
    sc_out< sc_logic > thresholds_Clk_A;
    sc_out< sc_logic > thresholds_Rst_A;
    sc_out< sc_lv<32> > outData_Addr_A;
    sc_out< sc_logic > outData_EN_A;
    sc_out< sc_lv<4> > outData_WEN_A;
    sc_out< sc_lv<32> > outData_Din_A;
    sc_in< sc_lv<32> > outData_Dout_A;
    sc_out< sc_logic > outData_Clk_A;
    sc_out< sc_logic > outData_Rst_A;
>>>>>>> e6ba4f12a62ab2691c7c4dd9af72e186add2c2fa


    // Module declarations
    openhab_controls(sc_module_name name);
    SC_HAS_PROCESS(openhab_controls);

    ~openhab_controls();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    regslice_both<32>* regslice_both_inStream_V_data_V_U;
    regslice_both<4>* regslice_both_inStream_V_keep_V_U;
    regslice_both<4>* regslice_both_inStream_V_strb_V_U;
    regslice_both<1>* regslice_both_inStream_V_user_V_U;
    regslice_both<1>* regslice_both_inStream_V_last_V_U;
    regslice_both<1>* regslice_both_inStream_V_id_V_U;
    regslice_both<1>* regslice_both_inStream_V_dest_V_U;
    regslice_both<32>* regslice_both_outStream_V_data_V_U;
    regslice_both<4>* regslice_both_outStream_V_keep_V_U;
    regslice_both<4>* regslice_both_outStream_V_strb_V_U;
    regslice_both<1>* regslice_both_outStream_V_user_V_U;
    regslice_both<1>* regslice_both_outStream_V_last_V_U;
    regslice_both<1>* regslice_both_outStream_V_id_V_U;
    regslice_both<1>* regslice_both_outStream_V_dest_V_U;
    sc_signal< sc_logic > ap_rst_n_inv;
<<<<<<< HEAD
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > inStream_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln16_fu_152_p2;
    sc_signal< sc_logic > outStream_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<5> > i_fu_158_p2;
    sc_signal< sc_lv<5> > i_reg_225;
    sc_signal< sc_logic > regslice_both_outStream_V_data_V_U_apdone_blk;
    sc_signal< bool > ap_block_state2;
    sc_signal< bool > ap_block_state2_io;
    sc_signal< sc_lv<32> > tmp_data_V_reg_230;
    sc_signal< sc_lv<64> > zext_ln26_fu_199_p1;
    sc_signal< sc_lv<64> > zext_ln26_reg_266;
    sc_signal< sc_lv<5> > i_0_reg_141;
    sc_signal< sc_lv<32> > thresholds_V_Addr_A_orig;
    sc_signal< sc_lv<32> > outData_V_Addr_A_orig;
    sc_signal< sc_lv<1> > signbit_fu_204_p2;
    sc_signal< sc_lv<17> > shl_ln_fu_209_p3;
    sc_signal< sc_lv<3> > ap_NS_fsm;
=======
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > inStream_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > outStream_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<4> > i_fu_154_p2;
    sc_signal< sc_lv<4> > i_reg_214;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > regslice_both_outStream_V_data_V_U_apdone_blk;
    sc_signal< sc_lv<64> > zext_ln19_fu_160_p1;
    sc_signal< sc_lv<64> > zext_ln19_reg_219;
    sc_signal< sc_lv<1> > icmp_ln14_fu_148_p2;
    sc_signal< sc_lv<32> > valOut_data_V_fu_205_p1;
    sc_signal< sc_lv<4> > i_0_reg_137;
    sc_signal< sc_lv<32> > thresholds_Addr_A_orig;
    sc_signal< sc_lv<32> > outData_Addr_A_orig;
    sc_signal< sc_lv<1> > icmp_ln887_fu_199_p2;
    sc_signal< sc_lv<4> > ap_NS_fsm;
>>>>>>> e6ba4f12a62ab2691c7c4dd9af72e186add2c2fa
    sc_signal< sc_logic > regslice_both_inStream_V_data_V_U_apdone_blk;
    sc_signal< sc_lv<32> > inStream_TDATA_int;
    sc_signal< sc_logic > inStream_TVALID_int;
    sc_signal< sc_logic > inStream_TREADY_int;
    sc_signal< sc_logic > regslice_both_inStream_V_data_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_keep_V_U_apdone_blk;
    sc_signal< sc_lv<4> > inStream_TKEEP_int;
    sc_signal< sc_logic > regslice_both_inStream_V_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_keep_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_strb_V_U_apdone_blk;
    sc_signal< sc_lv<4> > inStream_TSTRB_int;
    sc_signal< sc_logic > regslice_both_inStream_V_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_strb_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_user_V_U_apdone_blk;
    sc_signal< sc_lv<1> > inStream_TUSER_int;
    sc_signal< sc_logic > regslice_both_inStream_V_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_user_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_last_V_U_apdone_blk;
    sc_signal< sc_lv<1> > inStream_TLAST_int;
    sc_signal< sc_logic > regslice_both_inStream_V_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_last_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_id_V_U_apdone_blk;
    sc_signal< sc_lv<1> > inStream_TID_int;
    sc_signal< sc_logic > regslice_both_inStream_V_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_id_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_dest_V_U_apdone_blk;
    sc_signal< sc_lv<1> > inStream_TDEST_int;
    sc_signal< sc_logic > regslice_both_inStream_V_dest_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_dest_V_U_ack_in;
    sc_signal< sc_logic > outStream_TVALID_int;
    sc_signal< sc_logic > outStream_TREADY_int;
    sc_signal< sc_logic > regslice_both_outStream_V_data_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_keep_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_keep_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_strb_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_strb_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_user_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_user_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_last_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_last_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_id_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_id_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_dest_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_dest_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_dest_V_U_vld_out;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
<<<<<<< HEAD
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<5> ap_const_lv5_14;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<1> ap_const_lv1_1;
=======
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
>>>>>>> e6ba4f12a62ab2691c7c4dd9af72e186add2c2fa
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
<<<<<<< HEAD
    void thread_ap_block_state2();
    void thread_ap_block_state2_io();
=======
    void thread_ap_CS_fsm_state4();
>>>>>>> e6ba4f12a62ab2691c7c4dd9af72e186add2c2fa
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
<<<<<<< HEAD
    void thread_i_fu_158_p2();
    void thread_icmp_ln16_fu_152_p2();
    void thread_inStream_TDATA_blk_n();
    void thread_inStream_TREADY();
    void thread_inStream_TREADY_int();
    void thread_outData_V_Addr_A();
    void thread_outData_V_Addr_A_orig();
    void thread_outData_V_Clk_A();
    void thread_outData_V_Din_A();
    void thread_outData_V_EN_A();
    void thread_outData_V_Rst_A();
    void thread_outData_V_WEN_A();
    void thread_outStream_TDATA_blk_n();
    void thread_outStream_TVALID();
    void thread_outStream_TVALID_int();
    void thread_shl_ln_fu_209_p3();
    void thread_signbit_fu_204_p2();
    void thread_thresholds_V_Addr_A();
    void thread_thresholds_V_Addr_A_orig();
    void thread_thresholds_V_Clk_A();
    void thread_thresholds_V_Din_A();
    void thread_thresholds_V_EN_A();
    void thread_thresholds_V_Rst_A();
    void thread_thresholds_V_WEN_A();
    void thread_zext_ln26_fu_199_p1();
=======
    void thread_i_fu_154_p2();
    void thread_icmp_ln14_fu_148_p2();
    void thread_icmp_ln887_fu_199_p2();
    void thread_inStream_TDATA_blk_n();
    void thread_inStream_TREADY();
    void thread_inStream_TREADY_int();
    void thread_outData_Addr_A();
    void thread_outData_Addr_A_orig();
    void thread_outData_Clk_A();
    void thread_outData_Din_A();
    void thread_outData_EN_A();
    void thread_outData_Rst_A();
    void thread_outData_WEN_A();
    void thread_outStream_TDATA_blk_n();
    void thread_outStream_TVALID();
    void thread_outStream_TVALID_int();
    void thread_thresholds_Addr_A();
    void thread_thresholds_Addr_A_orig();
    void thread_thresholds_Clk_A();
    void thread_thresholds_Din_A();
    void thread_thresholds_EN_A();
    void thread_thresholds_Rst_A();
    void thread_thresholds_WEN_A();
    void thread_valOut_data_V_fu_205_p1();
    void thread_zext_ln19_fu_160_p1();
>>>>>>> e6ba4f12a62ab2691c7c4dd9af72e186add2c2fa
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
