#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("inStream_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("inStream_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("inStream_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("inStream_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("inStream_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("inStream_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("inStream_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("inStream_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("inStream_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("outStream_TDATA", 32, hls_out, 7, "axis", "out_data", 1),
	Port_Property("outStream_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("outStream_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
	Port_Property("outStream_TKEEP", 4, hls_out, 8, "axis", "out_data", 1),
	Port_Property("outStream_TSTRB", 4, hls_out, 9, "axis", "out_data", 1),
	Port_Property("outStream_TUSER", 1, hls_out, 10, "axis", "out_data", 1),
	Port_Property("outStream_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("outStream_TID", 1, hls_out, 12, "axis", "out_data", 1),
	Port_Property("outStream_TDEST", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("thresholds_V_Addr_A", 32, hls_out, 14, "bram", "MemPortADDR2", 1),
	Port_Property("thresholds_V_EN_A", 1, hls_out, 14, "bram", "MemPortCE2", 1),
	Port_Property("thresholds_V_WEN_A", 4, hls_out, 14, "bram", "MemPortWE2", 1),
	Port_Property("thresholds_V_Din_A", 32, hls_out, 14, "bram", "MemPortDIN2", 1),
	Port_Property("thresholds_V_Dout_A", 32, hls_in, 14, "bram", "MemPortDOUT2", 1),
	Port_Property("thresholds_V_Clk_A", 1, hls_out, 14, "bram", "mem_clk", 1),
	Port_Property("thresholds_V_Rst_A", 1, hls_out, 14, "bram", "mem_rst", 1),
	Port_Property("outData_V_Addr_A", 32, hls_out, 15, "bram", "MemPortADDR2", 1),
	Port_Property("outData_V_EN_A", 1, hls_out, 15, "bram", "MemPortCE2", 1),
	Port_Property("outData_V_WEN_A", 4, hls_out, 15, "bram", "MemPortWE2", 1),
	Port_Property("outData_V_Din_A", 32, hls_out, 15, "bram", "MemPortDIN2", 1),
	Port_Property("outData_V_Dout_A", 32, hls_in, 15, "bram", "MemPortDOUT2", 1),
	Port_Property("outData_V_Clk_A", 1, hls_out, 15, "bram", "mem_clk", 1),
	Port_Property("outData_V_Rst_A", 1, hls_out, 15, "bram", "mem_rst", 1),
};
const char* HLS_Design_Meta::dut_name = "openhab_controls";
