// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="openhab_controls,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.815000,HLS_SYN_LAT=51,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=50,HLS_SYN_LUT=107,HLS_VERSION=2019_2}" *)

module openhab_controls (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inStream_TDATA,
        inStream_TVALID,
        inStream_TREADY,
        inStream_TKEEP,
        inStream_TSTRB,
        inStream_TUSER,
        inStream_TLAST,
        inStream_TID,
        inStream_TDEST,
        outStream_TDATA,
        outStream_TVALID,
        outStream_TREADY,
        outStream_TKEEP,
        outStream_TSTRB,
        outStream_TUSER,
        outStream_TLAST,
        outStream_TID,
        outStream_TDEST,
        thresholds_V_Addr_A,
        thresholds_V_EN_A,
        thresholds_V_WEN_A,
        thresholds_V_Din_A,
        thresholds_V_Dout_A,
        thresholds_V_Clk_A,
        thresholds_V_Rst_A,
        outData_V_Addr_A,
        outData_V_EN_A,
        outData_V_WEN_A,
        outData_V_Din_A,
        outData_V_Dout_A,
        outData_V_Clk_A,
        outData_V_Rst_A
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] inStream_TDATA;
input   inStream_TVALID;
output   inStream_TREADY;
input  [3:0] inStream_TKEEP;
input  [3:0] inStream_TSTRB;
input  [0:0] inStream_TUSER;
input  [0:0] inStream_TLAST;
input  [0:0] inStream_TID;
input  [0:0] inStream_TDEST;
output  [31:0] outStream_TDATA;
output   outStream_TVALID;
input   outStream_TREADY;
output  [3:0] outStream_TKEEP;
output  [3:0] outStream_TSTRB;
output  [0:0] outStream_TUSER;
output  [0:0] outStream_TLAST;
output  [0:0] outStream_TID;
output  [0:0] outStream_TDEST;
output  [31:0] thresholds_V_Addr_A;
output   thresholds_V_EN_A;
output  [3:0] thresholds_V_WEN_A;
output  [31:0] thresholds_V_Din_A;
input  [31:0] thresholds_V_Dout_A;
output   thresholds_V_Clk_A;
output   thresholds_V_Rst_A;
output  [31:0] outData_V_Addr_A;
output   outData_V_EN_A;
output  [3:0] outData_V_WEN_A;
output  [31:0] outData_V_Din_A;
input  [31:0] outData_V_Dout_A;
output   outData_V_Clk_A;
output   outData_V_Rst_A;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg inStream_TREADY;
reg thresholds_V_EN_A;
reg outData_V_EN_A;
reg[3:0] outData_V_WEN_A;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    inStream_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln16_fu_152_p2;
reg    outStream_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire   [4:0] i_fu_158_p2;
reg   [4:0] i_reg_225;
wire    regslice_both_outStream_V_data_V_U_apdone_blk;
reg    ap_block_state2;
reg    ap_block_state2_io;
reg   [31:0] tmp_data_V_reg_230;
wire   [63:0] zext_ln26_fu_199_p1;
reg   [63:0] zext_ln26_reg_266;
reg   [4:0] i_0_reg_141;
wire   [31:0] thresholds_V_Addr_A_orig;
wire   [31:0] outData_V_Addr_A_orig;
wire   [0:0] signbit_fu_204_p2;
wire   [16:0] shl_ln_fu_209_p3;
reg   [2:0] ap_NS_fsm;
wire    regslice_both_inStream_V_data_V_U_apdone_blk;
wire   [31:0] inStream_TDATA_int;
wire    inStream_TVALID_int;
reg    inStream_TREADY_int;
wire    regslice_both_inStream_V_data_V_U_ack_in;
wire    regslice_both_inStream_V_keep_V_U_apdone_blk;
wire   [3:0] inStream_TKEEP_int;
wire    regslice_both_inStream_V_keep_V_U_vld_out;
wire    regslice_both_inStream_V_keep_V_U_ack_in;
wire    regslice_both_inStream_V_strb_V_U_apdone_blk;
wire   [3:0] inStream_TSTRB_int;
wire    regslice_both_inStream_V_strb_V_U_vld_out;
wire    regslice_both_inStream_V_strb_V_U_ack_in;
wire    regslice_both_inStream_V_user_V_U_apdone_blk;
wire   [0:0] inStream_TUSER_int;
wire    regslice_both_inStream_V_user_V_U_vld_out;
wire    regslice_both_inStream_V_user_V_U_ack_in;
wire    regslice_both_inStream_V_last_V_U_apdone_blk;
wire   [0:0] inStream_TLAST_int;
wire    regslice_both_inStream_V_last_V_U_vld_out;
wire    regslice_both_inStream_V_last_V_U_ack_in;
wire    regslice_both_inStream_V_id_V_U_apdone_blk;
wire   [0:0] inStream_TID_int;
wire    regslice_both_inStream_V_id_V_U_vld_out;
wire    regslice_both_inStream_V_id_V_U_ack_in;
wire    regslice_both_inStream_V_dest_V_U_apdone_blk;
wire   [0:0] inStream_TDEST_int;
wire    regslice_both_inStream_V_dest_V_U_vld_out;
wire    regslice_both_inStream_V_dest_V_U_ack_in;
reg    outStream_TVALID_int;
wire    outStream_TREADY_int;
wire    regslice_both_outStream_V_data_V_U_vld_out;
wire    regslice_both_outStream_V_keep_V_U_apdone_blk;
wire    regslice_both_outStream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_keep_V_U_vld_out;
wire    regslice_both_outStream_V_strb_V_U_apdone_blk;
wire    regslice_both_outStream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_strb_V_U_vld_out;
wire    regslice_both_outStream_V_user_V_U_apdone_blk;
wire    regslice_both_outStream_V_user_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_user_V_U_vld_out;
wire    regslice_both_outStream_V_last_V_U_apdone_blk;
wire    regslice_both_outStream_V_last_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_last_V_U_vld_out;
wire    regslice_both_outStream_V_id_V_U_apdone_blk;
wire    regslice_both_outStream_V_id_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_id_V_U_vld_out;
wire    regslice_both_outStream_V_dest_V_U_apdone_blk;
wire    regslice_both_outStream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_dest_V_U_vld_out;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
end

regslice_both #(
    .DataWidth( 32 ))
regslice_both_inStream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TDATA),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_data_V_U_ack_in),
    .data_out(inStream_TDATA_int),
    .vld_out(inStream_TVALID_int),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_inStream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TKEEP),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_keep_V_U_ack_in),
    .data_out(inStream_TKEEP_int),
    .vld_out(regslice_both_inStream_V_keep_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_inStream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TSTRB),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_strb_V_U_ack_in),
    .data_out(inStream_TSTRB_int),
    .vld_out(regslice_both_inStream_V_strb_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TUSER),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_user_V_U_ack_in),
    .data_out(inStream_TUSER_int),
    .vld_out(regslice_both_inStream_V_user_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TLAST),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_last_V_U_ack_in),
    .data_out(inStream_TLAST_int),
    .vld_out(regslice_both_inStream_V_last_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TID),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_id_V_U_ack_in),
    .data_out(inStream_TID_int),
    .vld_out(regslice_both_inStream_V_id_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TDEST),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_dest_V_U_ack_in),
    .data_out(inStream_TDEST_int),
    .vld_out(regslice_both_inStream_V_dest_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_dest_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 32 ))
regslice_both_outStream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TDATA_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(outStream_TREADY_int),
    .data_out(outStream_TDATA),
    .vld_out(regslice_both_outStream_V_data_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_outStream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TKEEP_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_keep_V_U_ack_in_dummy),
    .data_out(outStream_TKEEP),
    .vld_out(regslice_both_outStream_V_keep_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_outStream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TSTRB_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_strb_V_U_ack_in_dummy),
    .data_out(outStream_TSTRB),
    .vld_out(regslice_both_outStream_V_strb_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_outStream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TUSER_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_user_V_U_ack_in_dummy),
    .data_out(outStream_TUSER),
    .vld_out(regslice_both_outStream_V_user_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_outStream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TLAST_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_last_V_U_ack_in_dummy),
    .data_out(outStream_TLAST),
    .vld_out(regslice_both_outStream_V_last_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_outStream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TID_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_id_V_U_ack_in_dummy),
    .data_out(outStream_TID),
    .vld_out(regslice_both_outStream_V_id_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_outStream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TDEST_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_dest_V_U_ack_in_dummy),
    .data_out(outStream_TDEST),
    .vld_out(regslice_both_outStream_V_dest_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((outStream_TREADY_int == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_reg_141 <= i_reg_225;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_141 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_225 <= i_fu_158_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0))) & (icmp_ln16_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_data_V_reg_230 <= inStream_TDATA_int;
        zext_ln26_reg_266[4 : 0] <= zext_ln26_fu_199_p1[4 : 0];
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0))) & (icmp_ln16_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0))) & (icmp_ln16_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln16_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        inStream_TDATA_blk_n = inStream_TVALID_int;
    end else begin
        inStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((inStream_TVALID == 1'b1) & (regslice_both_inStream_V_data_V_U_ack_in == 1'b1))) begin
        inStream_TREADY = 1'b1;
    end else begin
        inStream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0))) & (icmp_ln16_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        inStream_TREADY_int = 1'b1;
    end else begin
        inStream_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if (((outStream_TREADY_int == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        outData_V_EN_A = 1'b1;
    end else begin
        outData_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((outStream_TREADY_int == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        outData_V_WEN_A = 4'd15;
    end else begin
        outData_V_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln16_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        outStream_TDATA_blk_n = outStream_TREADY_int;
    end else begin
        outStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0))) & (icmp_ln16_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        outStream_TVALID_int = 1'b1;
    end else begin
        outStream_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        thresholds_V_EN_A = 1'b1;
    end else begin
        thresholds_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0))) & (icmp_ln16_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((1'b1 == ap_block_state2_io) | (regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0))) & (icmp_ln16_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((outStream_TREADY_int == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state2 = ((regslice_both_outStream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln16_fu_152_p2 == 1'd0) & (inStream_TVALID_int == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln16_fu_152_p2 == 1'd0) & (outStream_TREADY_int == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign i_fu_158_p2 = (i_0_reg_141 + 5'd1);

assign icmp_ln16_fu_152_p2 = ((i_0_reg_141 == 5'd25) ? 1'b1 : 1'b0);

assign outData_V_Addr_A = outData_V_Addr_A_orig << 32'd2;

assign outData_V_Addr_A_orig = zext_ln26_reg_266;

assign outData_V_Clk_A = ap_clk;

assign outData_V_Din_A = shl_ln_fu_209_p3;

assign outData_V_Rst_A = ap_rst_n_inv;

assign outStream_TVALID = regslice_both_outStream_V_data_V_U_vld_out;

assign shl_ln_fu_209_p3 = {{signbit_fu_204_p2}, {16'd0}};

assign signbit_fu_204_p2 = (($signed(tmp_data_V_reg_230) < $signed(thresholds_V_Dout_A)) ? 1'b1 : 1'b0);

assign thresholds_V_Addr_A = thresholds_V_Addr_A_orig << 32'd2;

assign thresholds_V_Addr_A_orig = zext_ln26_fu_199_p1;

assign thresholds_V_Clk_A = ap_clk;

assign thresholds_V_Din_A = 32'd0;

assign thresholds_V_Rst_A = ap_rst_n_inv;

assign thresholds_V_WEN_A = 4'd0;

assign zext_ln26_fu_199_p1 = i_0_reg_141;

always @ (posedge ap_clk) begin
    zext_ln26_reg_266[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //openhab_controls
