// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="openhab_controls_bram,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.691000,HLS_SYN_LAT=21,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=15,HLS_SYN_LUT=80,HLS_VERSION=2019_2}" *)

module openhab_controls_bram (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inputData_V_Addr_A,
        inputData_V_EN_A,
        inputData_V_WEN_A,
        inputData_V_Din_A,
        inputData_V_Dout_A,
        inputData_V_Clk_A,
        inputData_V_Rst_A,
        thresholds_V_Addr_A,
        thresholds_V_EN_A,
        thresholds_V_WEN_A,
        thresholds_V_Din_A,
        thresholds_V_Dout_A,
        thresholds_V_Clk_A,
        thresholds_V_Rst_A,
        outData_Addr_A,
        outData_EN_A,
        outData_WEN_A,
        outData_Din_A,
        outData_Dout_A,
        outData_Clk_A,
        outData_Rst_A
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] inputData_V_Addr_A;
output   inputData_V_EN_A;
output  [3:0] inputData_V_WEN_A;
output  [31:0] inputData_V_Din_A;
input  [31:0] inputData_V_Dout_A;
output   inputData_V_Clk_A;
output   inputData_V_Rst_A;
output  [31:0] thresholds_V_Addr_A;
output   thresholds_V_EN_A;
output  [3:0] thresholds_V_WEN_A;
output  [31:0] thresholds_V_Din_A;
input  [31:0] thresholds_V_Dout_A;
output   thresholds_V_Clk_A;
output   thresholds_V_Rst_A;
output  [31:0] outData_Addr_A;
output   outData_EN_A;
output  [3:0] outData_WEN_A;
output  [31:0] outData_Din_A;
input  [31:0] outData_Dout_A;
output   outData_Clk_A;
output   outData_Rst_A;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg inputData_V_EN_A;
reg thresholds_V_EN_A;
reg outData_EN_A;
reg[3:0] outData_WEN_A;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] i_fu_88_p2;
reg   [3:0] i_reg_114;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln18_1_fu_94_p1;
reg   [63:0] zext_ln18_1_reg_119;
wire   [0:0] icmp_ln16_fu_82_p2;
reg   [3:0] i_0_reg_71;
wire    ap_CS_fsm_state3;
wire   [31:0] inputData_V_Addr_A_orig;
wire   [31:0] thresholds_V_Addr_A_orig;
wire   [31:0] outData_Addr_A_orig;
wire   [0:0] icmp_ln1495_fu_100_p2;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_reg_71 <= i_reg_114;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_71 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_114 <= i_fu_88_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln18_1_reg_119[3 : 0] <= zext_ln18_1_fu_94_p1[3 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln16_fu_82_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln16_fu_82_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        inputData_V_EN_A = 1'b1;
    end else begin
        inputData_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        outData_EN_A = 1'b1;
    end else begin
        outData_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        outData_WEN_A = 4'd15;
    end else begin
        outData_WEN_A = 4'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        thresholds_V_EN_A = 1'b1;
    end else begin
        thresholds_V_EN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln16_fu_82_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign i_fu_88_p2 = (i_0_reg_71 + 4'd1);

assign icmp_ln1495_fu_100_p2 = (($signed(inputData_V_Dout_A) < $signed(thresholds_V_Dout_A)) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_82_p2 = ((i_0_reg_71 == 4'd10) ? 1'b1 : 1'b0);

assign inputData_V_Addr_A = inputData_V_Addr_A_orig << 32'd2;

assign inputData_V_Addr_A_orig = zext_ln18_1_fu_94_p1;

assign inputData_V_Clk_A = ap_clk;

assign inputData_V_Din_A = 32'd0;

assign inputData_V_Rst_A = ap_rst;

assign inputData_V_WEN_A = 4'd0;

assign outData_Addr_A = outData_Addr_A_orig << 32'd2;

assign outData_Addr_A_orig = zext_ln18_1_reg_119;

assign outData_Clk_A = ap_clk;

assign outData_Din_A = icmp_ln1495_fu_100_p2;

assign outData_Rst_A = ap_rst;

assign thresholds_V_Addr_A = thresholds_V_Addr_A_orig << 32'd2;

assign thresholds_V_Addr_A_orig = zext_ln18_1_fu_94_p1;

assign thresholds_V_Clk_A = ap_clk;

assign thresholds_V_Din_A = 32'd0;

assign thresholds_V_Rst_A = ap_rst;

assign thresholds_V_WEN_A = 4'd0;

assign zext_ln18_1_fu_94_p1 = i_0_reg_71;

always @ (posedge ap_clk) begin
    zext_ln18_1_reg_119[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //openhab_controls_bram
