// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _vector_multiplier_HH_
#define _vector_multiplier_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "vector_multiplier_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 5,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct vector_multiplier : public sc_module {
    // Port declarations 37
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > in_data_TDATA;
    sc_in< sc_logic > in_data_TVALID;
    sc_out< sc_logic > in_data_TREADY;
    sc_in< sc_lv<4> > in_data_TKEEP;
    sc_in< sc_lv<4> > in_data_TSTRB;
    sc_in< sc_lv<1> > in_data_TUSER;
    sc_in< sc_lv<1> > in_data_TLAST;
    sc_in< sc_lv<1> > in_data_TID;
    sc_in< sc_lv<1> > in_data_TDEST;
    sc_out< sc_lv<32> > out_data_TDATA;
    sc_out< sc_logic > out_data_TVALID;
    sc_in< sc_logic > out_data_TREADY;
    sc_out< sc_lv<4> > out_data_TKEEP;
    sc_out< sc_lv<4> > out_data_TSTRB;
    sc_out< sc_lv<1> > out_data_TUSER;
    sc_out< sc_lv<1> > out_data_TLAST;
    sc_out< sc_lv<1> > out_data_TID;
    sc_out< sc_lv<1> > out_data_TDEST;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    vector_multiplier(sc_module_name name);
    SC_HAS_PROCESS(vector_multiplier);

    ~vector_multiplier();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    vector_multiplier_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* vector_multiplier_AXILiteS_s_axi_U;
    regslice_both<32>* regslice_both_in_data_data_V_U;
    regslice_both<4>* regslice_both_in_data_keep_V_U;
    regslice_both<4>* regslice_both_in_data_strb_V_U;
    regslice_both<1>* regslice_both_in_data_user_V_U;
    regslice_both<1>* regslice_both_in_data_last_V_U;
    regslice_both<1>* regslice_both_in_data_id_V_U;
    regslice_both<1>* regslice_both_in_data_dest_V_U;
    regslice_both<32>* regslice_both_out_data_data_V_U;
    regslice_both<4>* regslice_both_out_data_keep_V_U;
    regslice_both<4>* regslice_both_out_data_strb_V_U;
    regslice_both<1>* regslice_both_out_data_user_V_U;
    regslice_both<1>* regslice_both_out_data_last_V_U;
    regslice_both<1>* regslice_both_out_data_id_V_U;
    regslice_both<1>* regslice_both_out_data_dest_V_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > constant_V;
    sc_signal< sc_lv<32> > constant_V_0_data_reg;
    sc_signal< sc_logic > constant_V_0_vld_reg;
    sc_signal< sc_logic > constant_V_0_ack_out;
    sc_signal< sc_logic > in_data_TDATA_blk_n;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > out_data_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > in_data_data_V_tmp_reg_141;
    sc_signal< sc_lv<4> > in_data_keep_V_tmp_reg_146;
    sc_signal< sc_lv<4> > in_data_strb_V_tmp_reg_151;
    sc_signal< sc_lv<1> > in_data_user_V_tmp_reg_156;
    sc_signal< sc_lv<1> > in_data_last_V_tmp_reg_161;
    sc_signal< sc_lv<1> > in_data_id_V_tmp_reg_166;
    sc_signal< sc_lv<1> > in_data_dest_V_tmp_reg_171;
    sc_signal< sc_lv<32> > mul_ln214_fu_135_p1;
    sc_signal< sc_logic > regslice_both_out_data_data_V_U_apdone_blk;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > regslice_both_in_data_data_V_U_apdone_blk;
    sc_signal< sc_lv<32> > in_data_TDATA_int;
    sc_signal< sc_logic > in_data_TVALID_int;
    sc_signal< sc_logic > in_data_TREADY_int;
    sc_signal< sc_logic > regslice_both_in_data_data_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_in_data_keep_V_U_apdone_blk;
    sc_signal< sc_lv<4> > in_data_TKEEP_int;
    sc_signal< sc_logic > regslice_both_in_data_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_in_data_keep_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_in_data_strb_V_U_apdone_blk;
    sc_signal< sc_lv<4> > in_data_TSTRB_int;
    sc_signal< sc_logic > regslice_both_in_data_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_in_data_strb_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_in_data_user_V_U_apdone_blk;
    sc_signal< sc_lv<1> > in_data_TUSER_int;
    sc_signal< sc_logic > regslice_both_in_data_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_in_data_user_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_in_data_last_V_U_apdone_blk;
    sc_signal< sc_lv<1> > in_data_TLAST_int;
    sc_signal< sc_logic > regslice_both_in_data_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_in_data_last_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_in_data_id_V_U_apdone_blk;
    sc_signal< sc_lv<1> > in_data_TID_int;
    sc_signal< sc_logic > regslice_both_in_data_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_in_data_id_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_in_data_dest_V_U_apdone_blk;
    sc_signal< sc_lv<1> > in_data_TDEST_int;
    sc_signal< sc_logic > regslice_both_in_data_dest_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_in_data_dest_V_U_ack_in;
    sc_signal< sc_lv<32> > out_data_TDATA_int;
    sc_signal< sc_logic > out_data_TVALID_int;
    sc_signal< sc_logic > out_data_TREADY_int;
    sc_signal< sc_logic > regslice_both_out_data_data_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_out_data_keep_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_out_data_keep_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_out_data_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_out_data_strb_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_out_data_strb_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_out_data_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_out_data_user_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_out_data_user_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_out_data_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_out_data_last_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_out_data_last_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_out_data_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_out_data_id_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_out_data_id_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_out_data_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_out_data_dest_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_out_data_dest_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_out_data_dest_V_U_vld_out;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const int C_S_AXI_DATA_WIDTH;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_rst_n_inv();
    void thread_constant_V_0_ack_out();
    void thread_in_data_TDATA_blk_n();
    void thread_in_data_TREADY();
    void thread_in_data_TREADY_int();
    void thread_mul_ln214_fu_135_p1();
    void thread_out_data_TDATA_blk_n();
    void thread_out_data_TDATA_int();
    void thread_out_data_TVALID();
    void thread_out_data_TVALID_int();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
